//{id, name, title, date,paragraphs: []}

export const newsdata = [
  {
    id: "1",
    name: "MAN ELECTS 11TH PRESIDENT AT 5OTH ANNUAL GENERAL MEETING",
    title: "MAN ELECTS 11TH PRESIDENT AT 5OTH ANNUAL GENERAL MEETING",
    date: "October 24,2022",
    paragraphs: [
      "The Manufacturers Association of Nigeria (MAN) has elected Otunba Francis Meshioye as its 11th President at the just concluded 50th Annual General Meeting held in Lagos, Nigeria. This followed the completion of the highly successful four-year tenure of Engr. Mansur Ahmed, OFR.",
      "The election of the new President took place during the 50th Annual General Meeting of the foremost business membership association held on Wednesday, October 19, 2022 in Lagos.",
      "The Manufacturers Association of Nigeria is an advocacy group with a vision “to be the key driver for Industrialization, sustainable Economic Growth and Development in Nigeria” and was established in 1971 as an umbrella Organization to protect and project the interest of manufacturing industries in Nigeria. It is a focal point for communication and consultation between industry on the one hand, and the government and general public on the other.",
      "Newly elected President, Otunba Francis Meshioye, is Executive Director, JMG Limited and some other business corporations, amongst which are, JMG Power Generators Limited, Jamara Operations Limited, Octopus Microfinance Bank and ET & F Investment Ltd. He is on the board of government parastatal and member of several government Committees. ",
      "Prior to becoming President of the Association, he served as Chairman of Infrastructure Committee; Chairman of MAN Ikeja Branch; Chairman, Finance and Establishment Committee and Vice President, Lagos Zone of the Association.",
      "The newly elected President, Otunba Francis Meshioye will bring his wealth of experiences in the Management of Corporate organisations to bear on the leadership of over 2,500 membership organization.",
      "He is an Alumnus of the Prestigious Federal University of Technology, Akure (FUTA) where he obtained Masters degree in Business administration (MBA) in Technology, Marketing and Business Strategy. He also holds a Master’s Degree in International Management as well as a Law Degree, both from University of Liverpool, England.",
    ],
  },
  {
    id: "2",
    name: "MAN POSITION ON CBN'S GUIDELINES ON e-VALUATION AND e-INVOICING",
    title:
      "MANUFACTURERS ASSOCIATION OF NIGERIA (MAN) CONCERNS OVER THE CENTRAL BANK OF NIGERIA (CBN) GUIDELINES ON e-VALUATION AND e-INVOICING",
    date: "January 31, 2022 ",
    paragraphs: [
      "Background",
      "The Manufacturers Association of Nigeria (MAN) has examined the recent circular issued by the Central Bank of Nigeria (CBN) with ref. no: TED/FEM/FPC/PUB/01/001 of 21st January, 2022 titled “GUIDELINES ON THE INTRODUCTION OF E-VALUATION, E-INVOICING FOR IMPORT AND EXPORT IN NIGERIA”.",
      "MAN appreciates the efforts of the CBN and by extension the Federal Government, to sanitize foreign trade transactions in Nigeria. Without a doubt, we are persuaded that   it has some measure of impact on the foreign exchange profile of the country, which appears to be a major reason for the guidelines.  It is however necessary that the apex Bank’s attention be drawn to some issues that require clarifications and others that should be reviewed. There is need to ensure that the CBN does not go ahead to implement the guidelines without accommodating the constructive inputs of stakeholders, especially those whose businesses would be negatively impacted.",
      "The Issues",
      "• We noted that the implementation date on the circular is scheduled for 1st February, 2022; whereas the guideline itself was issued on the 21st January, 2022.  This is just 11 days grace before implementation. This is rather hasty. A circular on monetary or fiscal guidelines requires adequate adjustment time. This is more so when it involves international trade and transactions; where a minimum of 90 days allowance of time is normally required, as many operators would have opened Form M and concluded deals either for import of export. Straightaway, one must say that transactions already embarked upon before the commencement of the guidelines should be exempted and the commencement date should be extended by a minimum of 90 days.  ",
      "• The new regulation is primarily aimed at achieving near accurate value of imports and exports in Nigeria. It says any Form M or NXP that bears a unit price in excess of 2.5% of the verified global checkmate price will not be approved. This is concerning as it will checkmate the opportunity of our exporters to derive higher value for their exports. Besides, we are worried about the determination of global price verification mechanism and benchmark prices.",
      "•What happens if some companies are able to negotiate better prices due to their scale of order and are able to get competitive lower prices? Will these competitive prices be within the benchmark? Clearly, this aspect of the policy will lead to several challenges on valuation down the line including a floodgate of valuation issues with Nigeria Customs Service (NCS).",
      "• We also seek clarification on paragraph D of the guidelines; wherein the CBN is directing that …” the content of the electronic invoice authenticated by Authorized Dealer Banks is only advisory for the Nigeria Customs Service (NCS)”. This means that the NCS may vary it, probably uplift the FOB when issuing the PAAR. MAN considers CBN and NCS as agencies of the Federal Government and hence should harmonized their functions in this regard. Otherwise, businesses and indeed our members, will be subjected to paying unnecessary and additional FOB upliftment by the Nigeria Customs Service. This is in addition to a situation that may arise where the CBN forces such importer or manufacturer to reduce its price if it is considered not in conformity with the benchmark pricing.",
      "• In paragraph H, the CBN directs supplier and buyers to transmit their authenticated invoices would be transmitted through the CBN appointed Service Provider to the Nigeria Single Window portal. While MAN considers this measure as a step to check perceived malpractices, we believed that the essence of Single Window’ policy is being diminished and this could introduce unnecessary bureaucracy with attendant multiple charges. We already contend with this type of anomaly and could ill afford any addition. It will also be a disincentive to local and foreign investors. ",
      "• Finally, the annual subscription fee charge of $350 per authentication by suppliers on the portal meant to maintain the system, is a clear disincentive to suppliers of imports to Nigeria, particularly raw materials and spares for manufacturers. This has potential of triggering a run-on Nigeria business by their foreign partners and simultaneously encourage these suppliers to look elsewhere in the region as well as the continent.",
      "Conclusion  ",
      "The Manufacturers Association of Nigeria (MAN) therefore, would appreciate that the CBN considers all the issues raised above and suspend the policy guidelines for now; as well as give adequate consideration for a stakeholders’ dialogue with a view to addressing the concerns. There should also be a clear, step-by-step process of transaction under the guidelines. This is necessary to ensure that government does not inadvertently create a regime of chaos that will decelerate the already low level of activity in the manufacturing sector in particular and the economy in general. We should avoid a situation that will give the regulators a leeway to ride roughshod over private business owners who are already groaning under an inclement operating environment.",
      "SEGUN AJAYI-KADIR, mni.",
      "DIRECTOR GENERAL",
    ],
  },
  {
    id: "3",
    name: "MAN POSITION ON SEPTEMBER MPC REPORT",
    title:
      "MAN PERSPECTIVE ON THE SEPTEMBER 27, 2022 DECISION OF THE MONETARY POLICY COMMITTEE (MPC) OF THE CENTRAL BANK OF NIGERIA",
    date: "",
    paragraphs: [
      "1.0 Preamble",
      "The Monetary Policy Committee (MPC) in Communique No. 144 of the Third Quarter 2022 meeting recognized the global economic tension occasioned by the Russian-Ukrainian war with the associated disruption of global supply chain, degenerating global financial situation and accelerating world inflation.",
      "Consequently, the Committee increased the Monetary Policy Rate (MPR) by 150 base points to 15.5% with an asymmetric corridor of +100/-700 basis points around the MPR; and Cash Reserve Requirement (CRR) by 750 base points to 32.5%; while retaining Liquidity Ratio at 30%. The increase was aimed at moderating the high inflationary pressure on the economy and narrow the gap between the hitherto MPR of 14% and inflation rate which stood at 20.52% in August 2022 in order to improve the level real interest rate. Of course, real interest rate is critical to prospective investors who would want optimize their investment earnings.",
      "2.0 Implications for the economy and manufacturing sector",
      "The increase in the two monetary parameters, MPR and CRR portends worrisome negative consequences for the manufacturing sector, some of which include: ",
      "➢   Increased cost of borrowing by manufacturers, further beyond the extant double-digit rate, which disincentivize new investments in the sector;",
      "➢   Increased factor costs which feed into high product prices, making the sector uncompetitive;",
      "➢ 	High product prices, which makes patronage to plummet and lead to huge inventory of unsold manufactured products in the sector.",
      "➢	 High inventory of manufactured products will trigger reverse effect in the sector as manufacturing capacity utilization, production, employment, profit and tax contribution to national building will decline.",
      "3.0 Going forward  ",
      "In consideration of the prevailing scenario around increase in interest rate and access to funds, tougher times are ahead for the productive sector. Clearly, the increase in MPR from 14% to 15.5% will rub-off negatively on other rates and dash the hope for a single digit lending rate for the productive sector in the economy. Moreover, the observed continuous contractionary monetary policy posture without complimentary fiscal support may not effectively reduce the prevailing inflationary pressure on the economy. This is not unconnected with the fact that the current increase in Consumer Price index as reported by NBS is not largely driven by monetary phenomenon, as self-inflicted weak foreign exchange rate management can be linked to the pressure.  ",
      "An experiential x-ray of the prevailing economic stance revealed that domestic output gap due to the inefficiency of the macroeconomy, unguided industry development, inclement and high-cost operating environment, exploitative regulatory ecosystem and some externalities are predominantly responsible for the rising inflation that the nation is experiencing. ",
      "4.0 Conclusion",
      "It is important that the monetary authority strategically set in motion mechanism for wholistic balancing of the real interest rate, which is critical to investment and not just following leading economies to adjust Interest rate without considering domestic peculiarities. Interest rate (MPR), Inflation and Exchange Rate are triadically critical to investment and production. Balancing the rates in line with local aspiration is therefore imperative.  Regrettably, at the moment, other contributory factors like insecurity and externalities induced food shortage; Government’s excessive drive for internally generated revenue, increase in interest rate in the US; unsustainable and unpragmatic interventions in the forex market; the acute shortage of forex and unfriendly exchange rates are not only fueling inflation, but seriously depressing industrial production.",
      "Consequently, MAN is hopeful that the CBN will creatively go beyond the conventional monetary management system, because global economic dynamics are changing and conventional measures may no longer be effective. In the light of the above, we recommend as follows:",
      "➢ 	Upscale the current efforts at improving the availability of development-oriented funds at single digit interest rate, prioritizing industries.",
      "➢ 	Promote a more robust production centric forex management and intervention in official forex market, leveraging on sustained increase in crude oil price in the global market;",
      "➢ 	Give priority attention to meeting forex requirement of the industries vital inputs that are not available locally, to sustain and ramp-up production;",
      "➢	 Intentionally promote monetary and fiscal policy fusion; that is, the Central Bank of Nigerian and the Federal Ministry of Finance, Budget & National Planning should jointly put complimentary measures in place in support of domestic manufacturing.",
      "➢ 	Emplace the framework that will facilitate harmonious implementation of relevant policy guidelines aimed at boosting productivity.",
      "Undoubtedly, the Implementation of these measures will enable industries to remain in business; increase aggregate output; improve contribution to GDP and ensure inclusive and sustainable economic growth.",
      "Segun Ajayi-Kadir, mni",
      "Director General",
    ],
  },
];
