//{id, name, location, date, amount}

export const trainingData = [
  {
    id: "1",
    name: "Export by Sea, Road and Air Made Easy - ECOWAS, AfCFTA and Diaspora Markets",
    location: "MAN HOUSE IKEJA",
    date: "29th - 30th March",
    amount: "N70,000 ",
  },
  {
    id: "2",
    name: "Integrated Environmental &Quality Management System Awareness Course (14001&9001)",
    location: "",
    date: "11th – 12th April",
    amount: "",
  },
  {
    id: "3",
    name: "Positioning your products on top of the Competition in Export Markets.",
    location: "",
    date: "26th -27th April",
    amount: "",
  },
  {
    id: "4",
    name: "Food Safety Management System",
    location: "",
    date: "10 th – 12th May",
    amount: "",
  },
  {
    id: "5",
    name: "Export for Non-Export Professionals",
    location: "",
    date: "30th -31st May",
    amount: "",
  },
  {
    id: "6",
    name: "Effective Organizational Development for Productivity in Manufacturing Industries",
    location: "",
    date: "13th -14th June",
    amount: "",
  },
  {
    id: "7",
    name: "Challenges and Lessons of Successful Exporters, and Why Others fail.",
    location: "",
    date: "28th - 29th June",
    amount: "",
  },
  {
    id: "8",
    name: "Total Productive Maintenance Management",
    location: "",
    date: "11th -12th July",
    amount: "",
  },
  {
    id: "9",
    name: "Food Defence Management System",
    location: "",
    date: "8 th – 9 th August",
    amount: "",
  },
  {
    id: "10",
    name: "Overcoming Major Problems in Export Business.",
    location: "",
    date: "29th 30th August",
    amount: "",
  },
  {
    id: "11",
    name: "Financial Capacity Building for Non-Finance Executives",
    location: "",
    date: "12th - 13th September",
    amount: "",
  },
  {
    id: "12",
    name: "Registration, Requirements and Selection Processes of Nigerian Products for Export Opportunities in Export Trade",
    location: "",
    date: "27th -28th September",
    amount: "",
  },
  {
    id: "13",
    name: "Consolidating Safety Management Practices for Optimal Productivity",
    location: "",
    date: "10th – 11th October",
    amount: "",
  },
  {
    id: "14",
    name: "Positioning your products on top of the Competition in Export Markets.",
    location: "",
    date: "25th - 26th October",
    amount: "",
  },
  {
    id: "15",
    name: "Procurement Management System",
    location: "",
    date: "8th - 9th November",
    amount: "",
  },
  {
    id: "16",
    name: "Export by Sea, Road and Air Made Easy- ECOWAS, AfCFTA and Diaspora Markets.",
    location: "",
    date: "29th -30th November",
    amount: "",
  },
];
