export const strategicNews = [
  {
    id: "1",
    name: "Creativity and Innovation Management Unit",
    title: "INNOVATION AND CREATIVITY AND HOW IT FEEDS INTO MANUFACTURING",
    link: "",
    image: "",
    freetext: [
      "The Creativity and Innovation Management Unit was newly created in MAN to aid the delivery of MAN Services to its member companies. One of the ways the Management of MAN is aiming at beefing up services rendered to member companies is looking at how members can stay ahead of competition.",
      "In the aftermath of the COVID-19 pandemic and the emergence of the current bilateral trade agreement among African Countries – AfCFTA, manufacturing companies are looking at maintaining productivity and staying ahead of competition. The establishment of a new normal boosted the demand for finished products around the world prompting manufacturing companies to invest time and money into technological innovations that will reduce resource wastage and machine downtime while simultaneously shifting to sustainable materials and green energy sources to reduce the carbon footprint of manufacturing facilities and the final products.",
      "“Being open to change and innovation, we can find new and innovative ways of doing things, and this will help us to stay ahead of the competition.”",
      "Innovation is the process of creating and implementing new ideas. The process of converting new and useful ideas into useful products; services/processes/methods of operation. Creativity is the ability to combine ideas in a unique way. It provides new ideas for quality improvement in manufacturing and innovation puts these ideas into action. Creativity is a prerequisite for innovation.  These changes are made possible through technology. Technological advancements in the manufacturing sector play a vital role in the growth of the world economy.",
      "The four types of innovation are; Sustaining or incremental innovation, Breakthrough innovation, Disruptive innovation and Basic research.",
      "Some of the manufacturing solutions engaged in tackling these challenges are data driven innovation intelligence that improves strategic decision making such as;",
      "1. Industrial Automation – Simplifies a wide variety of processes in the production line, makes hazardous tasks safer and generates significant cost-saving for factories.",
      "2. Additive Manufacturing – Efficient and quick method for converting a concept into the final product through a computer-aided designing (CAD) and 3D printing to reduce large production cost that paves way for mass production.",
      "3. Artificial Intelligence – Modern manufacturing equipment that provides companies with a multitude of data to solve the problem of analyzing vast amounts of data and generating valuable insights quickly.",
      "4. Industrial Internet of Things – Programmable logic controllers (PLC) and human-machine interfaces (HMI) that displays all data regarding the machine condition and enable changes in machine settings. It streamlines operations, reduce costs, and improve worker safety.",
      "5. Immersive Technology – Such as augmented reality (AR), overlays relevant information on a piece of machinery to guide the operator thereby reducing the skill gap inside factories.",
      "6. Big Data & Analytics – The vast amount of data that these analytics platforms process improves worker safety and efficiency while also simplifying product innovation and reducing costs.",
      "7. Cloud Computing – Enables on-premise users and remote workforces to collaborate in real-time. This approach in manufacturing improves manageability and reduces network maintenance.",
      "8. 5G – enable companies to set up smart factories that greatly rely on sensor technology.",
      "9. Wearables – Wearable devices like smartwatches, smart bands, and headsets improve the safety of workers by constantly monitoring movements on the factory floor and raising alarms in the event of a safety incident. The monitoring of shop floor movement also provides data that is useful in process improvements and layout designs.",
      "10. Green Manufacturing – These sustainable solutions make the final product green, ensure a long lifetime, and promote circularity.",
      "Innovation becomes very relevant when it births value addition. The end of innovation should lead to value addition to customers",
      "Some key benefits of innovation are: improved productivity, reduced costs, increased competitiveness, improved brand recognition and value, new partnerships and relationships and increased turnover and improved profitability.",
      "The Association hopes to explore these areas further through the newly created Innovation and Creativity Management Unit in other to bring about an excellent service delivery to its members.",
      "The Unit wishes to achieve these through awareness creation, information sharing, organizing interactive workshop/roundtables, collaboration, Partnership (locally and internationally), Exchange programme, Mentorship and Internship programmes with relevant organizations that will be of value addition to members companies.",
      "Please, ride along with us as we look forward to supporting the new, dynamic, resilient and formidable manufacturing industry emerging in Nigeria, Africa and globally.",
    ],
  },
  {
    id: "2",
    name: "Environment and Green Manufacturing Unit",
    title: "ENVIRONMENT AND GREEN MANUFACTURING UNIT OF MAN",
    link: "",
    image: "",
    freetext: [
      "Green manufacturing is the current global catchword and the importance in today's business world is well known. MAN is highly committed to espousing the cause of green manufacturing and therefore, encourages and guides its members to making significant progress in this regard.",
      "Consequently, the Environment and Green Manufacturing Unit of MAN was strategically created in December 2022 with the responsibility of stirring awareness among MAN members on climate change issues; Environmental Management System (EMS) as well as providing members with strategies and necessary information needed to ameliorate the negative impacts of their production activities on the environment.",
      "The primary objective of the Unit amongst others is to provide necessary awareness on how MAN members can stay above the curve and continually maintain a competitive edge as the world transits to zero emission . This would be achieved by deploying innovative processes and leading technologies that provide both environmental and business benefits. ",
      "OPERATIONAL FRAMEWORK ",
      "The operational framework of the unit is as follows:",
      "1. Sensitizing members in collaboration with relevant MDA’s, NGO, Institutions and International Agencies on the concept of Green Manufacturing and the need to go Green;",
      "2. Encouraging seamless transition of members manufacturing process through the assistance of relevant agencies and organizations to an eco-friendlier production process through the utilization of leading technologies and practices on the environment and create mechanisms for sustainable development;",
      "3. Supporting and facilitating the adaptation of clean and renewable energy by manufacturers while encouraging them to build and develop capacity in Environment and Green Manufacturing;",
      "4. Educating  members on how to capture and record their carbon foot prints in other to use it to obtain carbon credit;",
      "5. Getting manufacturers acquainted with existing global, national and local climate and environmental laws/policies and the need for compliance;",
      "6. Advocating for amendment through dialogue with relevant government agencies on climate/environmental laws that may be over bearing to manufacturers;",
      "STRATEGIES/METHODOLOGIES",
      "The following are some of the strategies/methodologies deployed by the unit in achieving its goals:",
      "1. Using survey instrument e.g. questionnaire to get the pulse of members on their level of awareness and preparedness on environmental and climate issues;",
      "2. Organizing Quarterly Dialogue session to discuss topical and burning environmental and climate issues with members while bringing in relevant MDA’s, private organization, international and local agencies covering environmental and climate issues;",
      "3. Conducting standard trainings specifically for Desk Officers of member-companies on Environmental and Climate issues;",
      "4. Creating a network/platform for all Environmental Desk Officers of member-companies for continuous exchange of ideas, knowledge and information.",
    ],
  },
  {
    id: "3",
    name: "MEMBERSHIP SATISFACTION AND MONITORING",
    title: "MEMBERSHIP SATISFACTION AND MONITORING",
    link: "",
    image: "",
    freetext: [
      "Membership Satisfaction and Monitoring Unit is one of the most important goals of an Association. Research reveals that members' dissatisfaction is the overwhelming reason why members quit the Association.",
      "Given the current context, the Leadership of MAN is aware of the prevailing harsh economic environment and its implications on the business of its esteemed members. ",
      "The Association will relentlessly address the challenges of the harsh business environment and put in untiring efforts to provide solutions to its members ",
      "To immensely boost the Association's advocacy and serve the members better, MAN has established a new unit named 'Membership Satisfaction and Monitoring'. The Unit is entrusted with the key responsibility of providing quick responses to issues that concern our members.",
      "However, members are encouraged to channel all their complaints and concern both recent and old to the Unit for prompt attention.",
    ],
  },
];
